=== MrMoose/paradium/htdocs/stations.dtd
<!ELEMENT stations
	(station*)>
<!ELEMENT station (name, url+, website?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT website (#PCDATA)>

=== MrMoose/paradium/htdocs/stations.xml
<?xml version="1.0" standalone="no" ?>
<!DOCTYPE stations SYSTEM "stations.dtd">

<stations>
	<station id="1">
		<!-- The one and only -->
        <name>Radio Paradise</name>
        <!-- Europe (UK) server -->
        <url>http://stream-uk1.radioparadise.com/aac-128</url>
        <!-- Russian server -->
        <url>http://stream-ru1.radioparadise.com:9000/aac-128</url>
		<website>http://www.radioparadise.com/ios-content.php</website>
    </station>
	<station id="2">
		<!-- Psychedelik has multiple streams this is called Ambient -->
        <name>Psychedelik/</name>
        <!-- seems to be only one -->
		<url>http://88.191.102.69:8002/;stream.mp3</url>
		<website>http://www.psychedelik.com/</website>
    </station>
	<station id="3">
		<!-- Burning Man informational radio -->
        <name>BMIR</name>
		<url>http://bmir-ice.streamguys.com/live</url>
		<website>http://www.bmir.org/</website>
    </station>
</stations>
